structure(list(method = "GET", url = "https://api.openalex.org/works/https://doi.org/10.1177%2Ffake?mailto=metacheck@scienceverse.org", 
    status_code = 404L, headers = structure(list(date = "Tue, 12 May 2026 21:03:29 GMT", 
        `content-type` = "text/html; charset=utf-8", `cf-ray` = "9fac5ed13b002196-MAN", 
        `cf-cache-status` = "DYNAMIC", `access-control-allow-origin` = "*", 
        server = "cloudflare", via = "1.1 heroku-router", `access-control-allow-headers` = "Accept, Accept-Language, Accept-Encoding, Authorization, Content-Type", 
        `access-control-allow-methods` = "GET, HEAD, POST, OPTIONS", 
        nel = "{\"report_to\":\"heroku-nel\",\"response_headers\":[\"Via\"],\"max_age\":3600,\"success_fraction\":0.01,\"failure_fraction\":0.1}", 
        `report-to` = "{\"group\":\"heroku-nel\",\"endpoints\":[{\"url\":\"https://nel.heroku.com/reports?s=DJGDIuUJ%2FwLHOjPMtv90fk7Lzhjjf8NTaGC78Hbneuo%3D\\u0026sid=c46efe9b-d3d2-4a0c-8c76-bfafa16c5add\\u0026ts=1778619809\"}],\"max_age\":3600}", 
        `reporting-endpoints` = "heroku-nel=\"https://nel.heroku.com/reports?s=DJGDIuUJ%2FwLHOjPMtv90fk7Lzhjjf8NTaGC78Hbneuo%3D&sid=c46efe9b-d3d2-4a0c-8c76-bfafa16c5add&ts=1778619809\"", 
        `x-ratelimit-cost-usd` = "0.0001", `x-ratelimit-credits-used` = "1", 
        `x-ratelimit-limit` = "10000", `x-ratelimit-limit-usd` = "1", 
        `x-ratelimit-onetime-remaining` = "0", `x-ratelimit-prepaid-remaining-usd` = "0", 
        `x-ratelimit-remaining` = "9925", `x-ratelimit-remaining-usd` = "0.9925", 
        `x-ratelimit-reset` = "10591", `access-control-expose-headers` = "Cache-Control, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Onetime-Remaining, X-RateLimit-Credits-Used, X-RateLimit-Credits-Required, X-RateLimit-Reset, X-RateLimit-Limit-USD, X-RateLimit-Remaining-USD, X-RateLimit-Prepaid-Remaining-USD, X-RateLimit-Cost-USD, X-RateLimit-Cost-Required-USD, Retry-After", 
        `content-encoding` = "gzip"), class = "httr2_headers"), 
    body = charToRaw("<!doctype html>\n<html lang=en>\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>\n"), 
    timing = c(redirect = 0, namelookup = 0, connect = 0, pretransfer = 0.000116, 
    starttransfer = 0.170988, total = 0.171096), cache = new.env(parent = emptyenv())), class = "httr2_response")
