structure(list(url = "https://files.osf.io/v1/resources/mc45x/providers/github/README.md", 
    status_code = 200L, headers = structure(list(server = "nginx", 
        date = "Sun, 17 Aug 2025 16:41:00 GMT", `content-type` = "text/x-markdown", 
        `content-length` = "36", `x-waterbutler-request-id` = "7acf44cb-e57c-479d-b778-fa59ca09b9fc", 
        `content-disposition` = "attachment; filename=\"README.md\"; filename*=UTF-8''README.md", 
        `cache-control` = "no-cache, no-store, max-age=0, must-revalidate", 
        expires = "-1", pragma = "no-cache", via = "1.1 google", 
        `alt-svc` = "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/2", 
        headers = structure(list(date = "Sun, 17 Aug 2025 16:40:56 GMT", 
            `content-type` = "text/html; charset=utf-8", `content-length` = "319", 
            location = "https://files.osf.io/v1/resources/mc45x/providers/github/README.md", 
            `x-frame-options` = "SAMEORIGIN", `x-cache-status` = "MISS", 
            `cache-control` = "no-cache, no-store, max-age=0, must-revalidate", 
            expires = "-1", pragma = "no-cache", `strict-transport-security` = "max-age=15724800", 
            `x-content-type-options` = "nosniff"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        server = "nginx", date = "Sun, 17 Aug 2025 16:41:00 GMT", 
        `content-type` = "text/x-markdown", `content-length` = "36", 
        `x-waterbutler-request-id` = "7acf44cb-e57c-479d-b778-fa59ca09b9fc", 
        `content-disposition` = "attachment; filename=\"README.md\"; filename*=UTF-8''README.md", 
        `cache-control` = "no-cache, no-store, max-age=0, must-revalidate", 
        expires = "-1", pragma = "no-cache", via = "1.1 google", 
        `alt-svc` = "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = structure(find_mock_file("osf.io/download/6891f2f7157709eae14783e1.R-FILE"), 
        class = "path"), date = structure(1755448860, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0.158214, 
    namelookup = 0.029147, connect = 0.034269, pretransfer = 0.045822, 
    starttransfer = 3.883238, total = 3.883522)), class = "response")
