structure(list(url = "https://pubpeer.com/v3/publications?devkey=PubPeerZotero", 
    status_code = 422L, headers = structure(list(server = "nginx", 
        `content-type` = "application/json", `access-control-allow-origin` = "*", 
        `access-control-allow-headers` = "Content-Type,X-Auth-Token,Authorization,Origin,x-csrf-token,x-requested-with", 
        `access-control-allow-methods` = "POST,PUT", `cache-control` = "no-cache, private", 
        date = "Mon, 08 Dec 2025 02:17:12 GMT", via = "1.1 google", 
        `alt-svc` = "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 422L, version = "HTTP/2", 
        headers = structure(list(server = "nginx", `content-type` = "application/json", 
            `access-control-allow-origin` = "*", `access-control-allow-headers` = "Content-Type,X-Auth-Token,Authorization,Origin,x-csrf-token,x-requested-with", 
            `access-control-allow-methods` = "POST,PUT", `cache-control` = "no-cache, private", 
            date = "Mon, 08 Dec 2025 02:17:12 GMT", via = "1.1 google", 
            `alt-svc` = "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"errors\":{\"dois\":[\"The dois field is required when none of pmids \\/ issns are present.\"],\"pmids\":[\"The pmids field is required when none of dois \\/ issns are present.\"],\"issns\":[\"The issns field is required when none of dois \\/ pmids are present.\"]},\"status\":\"bad\"}"), 
    date = structure(1765160232, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0, 
    connect = 0, pretransfer = 0.000228, starttransfer = 0.108672, 
    total = 0.109349)), class = "response")
