structure(list(method = "GET", url = "https://zenodo.org/api/records/00000000", 
    status_code = 404L, headers = structure(list(server = "nginx", 
        date = "Thu, 04 Jun 2026 16:19:40 GMT", `content-type` = "application/json", 
        `content-length` = "71", `access-control-allow-origin` = "*", 
        `access-control-expose-headers` = "Content-Type, ETag, Link, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset", 
        `x-ratelimit-limit` = "133", `x-ratelimit-remaining` = "130", 
        `x-ratelimit-reset` = "1780590041", `retry-after` = "60", 
        `permissions-policy` = "interest-cohort=()", `x-frame-options` = "sameorigin", 
        `x-xss-protection` = "1; mode=block", `x-content-type-options` = "nosniff", 
        `content-security-policy` = "default-src 'self' fonts.googleapis.com *.gstatic.com data: 'unsafe-inline' 'unsafe-eval' blob: zenodo-broker.web.cern.ch zenodo-broker-qa.web.cern.ch maxcdn.bootstrapcdn.com cdnjs.cloudflare.com ajax.googleapis.com webanalytics.web.cern.ch", 
        `strict-transport-security` = "max-age=31556926; includeSubDomains", 
        `referrer-policy` = "strict-origin-when-cross-origin"), class = "httr2_headers"), 
    body = charToRaw("{\"status\": 404, \"message\": \"The persistent identifier does not exist.\"}"), 
    timing = c(redirect = 0, namelookup = 0, connect = 0, pretransfer = 0.000116, 
    starttransfer = 0.054367, total = 0.054407), cache = new.env(parent = emptyenv())), class = "httr2_response")
