#' RegCheck Preregistration Comparison
#'
#' @description
#' Compare the preregistrations of a paper with the paper itself using
#' RegCheck, an LLM-based tool that judges, dimension by dimension, whether
#' the paper is consistent with what was preregistered.
#'
#' @details
#' The RegCheck module builds on the Preregistration Check module: it takes
#' the preregistration content retrieved by `prereg_check` and sends it,
#' together with the full paper text, to a
#' [RegCheck](https://github.com/JamieCummins/regcheck) server. RegCheck
#' compares the two documents on a set of dimensions (sample size,
#' hypotheses, exclusion criteria, etc.) and judges for each dimension
#' whether the paper deviates from the preregistration ("yes"), is consistent
#' with it ("no"), or whether there is insufficient information to tell
#' ("missing").
#'
#' You can chain the modules so the preregistrations are only retrieved once:
#' `paper |> module_run("prereg_check") |> module_run("reg_check")`. If you
#' run `reg_check` on its own, it runs `prereg_check` for you first.
#'
#' By default the comparison uses the locally running
#' RegCheck server bundled inside metacheck with Ollama
#' (`client = "ollama"`, `http://localhost:8000`), so no text leaves your
#' machine. Set `client` to "groq", "openai" or "deepseek" to use the hosted
#' RegCheck app instead; note that this sends the full paper and
#' preregistration text to that server and the corresponding LLM provider.
#' All RegCheck servers (including a local one) require an API token in the
#' `REGCHECK_API_TOKEN` environment variable (see `?regcheck_compare`).
#'
#' Each comparison makes one LLM call per dimension and can take several
#' minutes per preregistration. The judgements are generated by a large
#' language model and are presented as pointers for manual checking, never as
#' automated conclusions.
#'
#' @keywords method
#'
#' @author Daniel Lakens (\email{D.Lakens@tue.nl})
#'
#' @import dplyr
#'
#' @param paper a paper object or paperlist object
#' @param client the LLM client RegCheck should use: "ollama" (local,
#'   default), "groq", "openai", or "deepseek"
#' @param base_url the base URL of the RegCheck server (defaults to
#'   http://localhost:8000 for ollama, the hosted RegCheck app otherwise)
#' @param dimensions optional data frame with columns `dimension` and
#'   `definition` to override RegCheck's default comparison dimensions
#'
#' @returns a list
reg_check <- function(paper,
                      client = "ollama",
                      base_url = NULL,
                      dimensions = NULL) {
  # chained: paper |> module_run("prereg_check") |> module_run("reg_check")

  # get prereg info ----
  # from a chained prereg_check run, or by running prereg_check now
  prereg_info <- get_prev_outputs("prereg_check", "table")
  if (is.null(prereg_info)) {
    prereg_out <- module_run(paper, "prereg_check")
    prereg_info <- prereg_out$table
  }

  ## no preregistrations ----
  if (is.null(prereg_info) || nrow(prereg_info) == 0) {
    resp <- list(
      traffic_light = "na",
      summary_text = "No preregistrations were found to compare with the paper.",
      na_replace = 0,
      summary_table = data.frame(
        paper_id = paper_id(paper),
        regcheck_deviations = 0
      )
    )
    return(resp)
  }

  # papers often link the same preregistration more than once, which gives
  # duplicate rows in prereg_info; compare each unique prereg only once
  dup <- duplicated(prereg_info[, c("paper_id", "id")])
  prereg_info <- prereg_info[!dup, , drop = FALSE]

  # compare each prereg with its paper ----
  rc_list <- list()
  rc_error <- NULL
  for (i in seq_len(nrow(prereg_info))) {
    pid <- prereg_info$paper_id[[i]]
    if (is.null(pid) || is.na(pid)) pid <- paper_id(paper)[[1]]
    p <- if (inherits(paper, "scivrs_paperlist")) paper[[pid]] else paper
    full_text <- paste(p$text$text, collapse = " ")
    prereg_text <- prereg_row_text(prereg_info[i, , drop = FALSE])

    message("RegCheck: comparing preregistration ", prereg_info$id[[i]],
            " with paper ", pid, " (this can take several minutes)")

    rc <- tryCatch(
      regcheck_compare(full_text, prereg_text,
                       client = client,
                       base_url = base_url,
                       dimensions = dimensions),
      error = function(e) e
    )

    if (inherits(rc, "error")) {
      rc_error <- conditionMessage(rc)
      message("RegCheck comparison failed for preregistration ",
              prereg_info$id[[i]], ": ", rc_error)
      next
    }

    if (nrow(rc) > 0) {
      rc$prereg_id <- prereg_info$id[[i]]
      rc$paper_id <- pid
      rc_list[[length(rc_list) + 1]] <- rc
    }
  }

  ## all comparisons failed ----
  if (length(rc_list) == 0) {
    # no na_replace here: a failed check is unknown (NA), not zero
    resp <- list(
      traffic_light = "error",
      summary_text = paste0(
        "We found ", nrow(prereg_info), " preregistration",
        plural(nrow(prereg_info)),
        ", but the RegCheck comparison failed",
        if (!is.null(rc_error)) paste0(": ", rc_error) else "", "."
      ),
      summary_table = data.frame(
        paper_id = paper_id(paper),
        regcheck_deviations = NA_real_
      )
    )
    return(resp)
  }

  regcheck_table <- do.call(dplyr::bind_rows, rc_list)

  # traffic light ----
  # judgements are LLM-generated information for human review, never an
  # automated verdict, so the light stays informational
  tl <- "info"

  # summary counts ----
  j <- tolower(trimws(regcheck_table$deviation_judgement))
  n_dev <- sum(j == "yes")
  n_unclear <- sum(j == "missing")
  n_prereg_compared <- length(unique(regcheck_table$prereg_id))

  summary_table <- data.frame(
    paper_id = regcheck_table$paper_id,
    j = j
  ) |>
    dplyr::summarise(
      .by = "paper_id",
      regcheck_deviations = sum(j == "yes"),
      regcheck_consistent = sum(j == "no"),
      regcheck_unclear = sum(j == "missing")
    )

  # summary text ----
  summary_text <- sprintf(
    "RegCheck compared the paper with %d preregistration%s on %d dimension%s, and flagged %d potential deviation%s (%d dimension%s not specified in the preregistration).",
    n_prereg_compared, plural(n_prereg_compared),
    nrow(regcheck_table), plural(nrow(regcheck_table)),
    n_dev, plural(n_dev),
    n_unclear, plural(n_unclear)
  )

  # report ----
  report_intro <- paste(
    summary_text,
    "These judgements are generated by a large language model: treat them as pointers for manual checking, not as conclusions, and always verify them against the original documents."
  )

  judgement_label <- c(
    yes = "deviation",
    no = "consistent",
    missing = "unclear"
  )

  strip_refs <- function(x) gsub("\\s*\\[[A-Z_0-9,; ]+\\]", "", x)

  prereg_sections <- lapply(
    unique(regcheck_table$prereg_id), \(rid) {
      sub <- regcheck_table[regcheck_table$prereg_id == rid, ]
      sub_j <- tolower(trimws(sub$deviation_judgement))
      labels <- judgement_label[sub_j]
      labels[is.na(labels)] <- sub$deviation_judgement[is.na(labels)]

      judgement_table <- data.frame(
        dimension = sub$dimension,
        judgement = unname(labels),
        explanation = strip_refs(sub$deviation_information)
      )
      evidence_table <- data.frame(
        dimension    = sub$dimension,
        paper_summary   = strip_refs(sub$paper_summary),
        prereg_summary  = strip_refs(sub$prereg_summary),
        paper_quotes    = strip_refs(sub$paper_quotes),
        prereg_quotes   = strip_refs(sub$prereg_quotes)
      )
      c(
        sprintf("Comparison with preregistration %s:", rid),
        scroll_table(judgement_table),
        collapse_section(
          scroll_table(evidence_table, maxrows = 5),
          sprintf("RegCheck evidence for %s", rid)
        )
      )
    }
  )

  ## guidance ----
  guidance <- c(
    "RegCheck was developed by Jamie Cummins (<https://github.com/JamieCummins/regcheck>); the local Ollama server bundled in metacheck is inspired by the Ollama integration work of Matilda Gustafsson (<https://github.com/Matilda03>).",
    "For metascientific articles demonstrating the rate of deviations from preregistrations, see:",
    format_ref(vandenAkker2024),
    "For educational material on how to report deviations from preregistrations, see:",
    format_ref(Lakens2024)
  )

  report <- c(
    report_intro,
    unlist(prereg_sections),
    collapse_section(guidance)
  )

  # return a list ----
  list(
    table = regcheck_table,
    summary_table = summary_table,
    na_replace = 0,
    traffic_light = tl,
    report = report,
    summary_text = summary_text
  )
}

# helper functions ----

## Flatten a prereg_info row to text for RegCheck ----
# one "field_name\nvalue" block per non-empty schema field, so RegCheck
# receives the full structured content of the preregistration
prereg_row_text <- function(row) {
  skip <- c("paper_id", "link", "ia_url")
  out <- character(0)
  for (nm in setdiff(names(row), skip)) {
    val <- row[[nm]]
    if (is.null(val) || length(val) == 0) next
    val <- as.character(val)[[1]]
    if (is.na(val) || !nzchar(trimws(val))) next
    out <- c(out, paste0(nm, "\n", val))
  }
  paste(out, collapse = "\n\n")
}

# references

vandenAkker2024 <- bibentry(
  bibtype = "Article",
  title = "The potential of preregistration in psychology: Assessing preregistration producibility and preregistration-study consistency",
  author = c(
    person("O. R.", "van den Akker"),
    person("M.", "Bakker"),
    person("M. A. L. M.", "van Assen"),
    person("C. R.", "Pennington"),
    person("L.", "Verweij"),
    person("M. M.", "Elsherif"),
    person("A.", "Claesen"),
    person("S. D. M.", "Gaillard"),
    person("S. K.", "Yeung"),
    person("J.-L.", "Frankenberger"),
    person("K.", "Krautter"),
    person("J. P.", "Cockcroft"),
    person("K. S.", "Kreuer"),
    person("T. R.", "Evans"),
    person("F. M.", "Heppel"),
    person("S. F.", "Schoch"),
    person("M.", "Korbmacher"),
    person("Y.", "Yamada"),
    person("N.", "Albayrak-Aydemir"),
    person("J. M.", "Wicherts")
  ),
  journal = "Psychological Methods",
  year = 2024,
  doi = "10.1037/met0000687"
)

Lakens2024 <- bibentry(
  bibtype = "Article",
  author  = "Lakens, Daniël",
  year    = 2024,
  title   = "When and How to Deviate From a Preregistration",
  journal = "Collabra: Psychology",
  volume  = 10,
  number  = 1,
  pages   = "117094",
  doi     = "10.1525/collabra.117094"
)
